AWSTemplateFormatVersion: '2010-09-09'
Description: A simple AWS CloudFormation template to create an SNS topic.
Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: My SNS Topic
      TopicName: my-sns-topic